In [89]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding, Dense, Dropout, LayerNormalization, MultiHeadAttention, Flatten, GlobalAveragePooling1D
from tensorflow.keras import Sequential, Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Layer
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import PolynomialDecay
from tensorflow.keras.losses import sparse_categorical_crossentropy
import numpy as np
import pandas as pd

In [90]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [91]:
# Hyperparameters
vocab_size = 3325  # Vocabulary size
input_seq_len = 100    # Maximum sequence length
output_seq_len = 1
embedding_dim = 512
num_heads = 8
ff_dim = 2048
num_layers = 5
dropout_rate = 0.2
batch_size = 8
epochs = 30

In [92]:
def load_data_single_csv(filepath):
    # Load the data
    df = pd.read_csv(filepath)

    df["Message + Username"] = df["Username"] + ": " + df["Message"]

    # Initialize a list to store the conversation history
    conversation_history = []

    # Store input-output pairs
    input_texts = []
    output_texts = []

    # Iterate through the dataframe to process the conversation
    for i in range(5, len(df)):
        # Get the context of the last 5 messages (this includes messages from others as well)
        context = df.iloc[i-5:i]['Message + Username'].tolist()
        
        # The current message is the output (label) only if it was sent by you
        if df.iloc[i]['Username'] == 'Pranav Kannepalli':
            # Join the context into a single string
            context_input =  '<GO> ' + '<SEP>'.join(context) + "<SEP> Pranav Kannepalli:"
            curr_message = str(df.iloc[i]['Message'])

            for i in curr_message.split(' '):
                input_texts.append(context_input)
                output_texts.append(i)
                
                context_input += ' ' + i
            
            input_texts.append(context_input)
            output_texts.append("<END>")

        
    # Create a DataFrame to store the final inputs and outputs
    training_data = pd.DataFrame({
        'input_text': input_texts,
        'output_label': output_texts
    })


    return training_data

training_data = pd.DataFrame()
for i in [2, 3]:
    filepath = f'./chat_csv\'s/chat{i}.csv'
    temp = load_data_single_csv(filepath)
    training_data = pd.concat((training_data, temp))

training_data

,input_text,output_label
0,<GO> tsa 25: Messages and calls are end-to-end...,image
1,<GO> tsa 25: Messages and calls are end-to-end...,omitted
2,<GO> tsa 25: Messages and calls are end-to-end...,<END>
3,<GO> tsa 25: You created group “tea 25”<SEP>Pr...,does
4,<GO> tsa 25: You created group “tea 25”<SEP>Pr...,anyone
...,...,...
2022,<GO> Pranav Kannepalli: sure that works for me...,possible?
2023,<GO> Pranav Kannepalli: sure that works for me...,<END>
2024,<GO> Pranav Kannepalli: Krishna uncle?<SEP>Kri...,sounds
2025,<GO> Pranav Kannepalli: Krishna uncle?<SEP>Kri...,good


In [93]:
def tokenize_and_pad(training_data):
    tokenizer = Tokenizer(num_words=vocab_size, oov_token='<OOV>')
    
    # Fit tokenizer on both input and output text
    tokenizer.fit_on_texts(training_data['input_text'].tolist() + training_data['output_label'].tolist())

    # Convert text to sequences
    input_sequences = tokenizer.texts_to_sequences(training_data['input_text'])
    output_sequences = tokenizer.texts_to_sequences(training_data['output_label'])
    
    # Pad sequences to ensure they are of equal length
    input_sequences = pad_sequences(input_sequences, maxlen=input_seq_len, padding='post', truncating='post')
    output_sequences = pad_sequences(output_sequences, maxlen=output_seq_len, padding='post', truncating='post')
    
    return input_sequences/len(tokenizer.word_index), output_sequences , tokenizer

input_sequences, output_sequences, tokenizer = tokenize_and_pad(training_data)
input_sequences, output_sequences

(array([[0.00240529, 0.03367408, 0.10162357, ..., 0.        , 0.        ,
         0.        ],
        [0.00240529, 0.03367408, 0.10162357, ..., 0.        , 0.        ,
         0.        ],
        [0.00240529, 0.03367408, 0.10162357, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.00240529, 0.00090198, 0.00120265, ..., 0.        , 0.        ,
         0.        ],
        [0.00240529, 0.00090198, 0.00120265, ..., 0.        , 0.        ,
         0.        ],
        [0.00240529, 0.00090198, 0.00120265, ..., 0.        , 0.        ,
         0.        ]]),
 array([[ 85],
        [ 84],
        [ 44],
        ...,
        [135],
        [ 51],
        [ 44]]))

In [94]:
flattened_data = output_sequences.flatten()

counts = []
for i in range(len(tokenizer.word_index)):
    counts.append(np.count_nonzero(flattened_data == i))


# Display the results
for number, count in enumerate(counts): 
    print(f"Number {number}: {count} times")

end_token = tokenizer.word_index['end']
end_token

Number 0: 20 times
Number 1: 0 times
Number 2: 0 times
Number 3: 2 times
Number 4: 0 times
Number 5: 12 times
Number 6: 0 times
Number 7: 350 times
Number 8: 21 times
Number 9: 351 times
Number 10: 14 times
Number 11: 272 times
Number 12: 215 times
Number 13: 245 times
Number 14: 196 times
Number 15: 180 times
Number 16: 65 times
Number 17: 187 times
Number 18: 181 times
Number 19: 177 times
Number 20: 151 times
Number 21: 13 times
Number 22: 100 times
Number 23: 127 times
Number 24: 0 times
Number 25: 115 times
Number 26: 120 times
Number 27: 113 times
Number 28: 111 times
Number 29: 103 times
Number 30: 0 times
Number 31: 0 times
Number 32: 0 times
Number 33: 91 times
Number 34: 53 times
Number 35: 84 times
Number 36: 65 times
Number 37: 115 times
Number 38: 81 times
Number 39: 73 times
Number 40: 87 times
Number 41: 45 times
Number 42: 20 times
Number 43: 64 times
Number 44: 2485 times
Number 45: 0 times
Number 46: 66 times
Number 47: 61 times
Number 48: 61 times
Number 49: 63 times

44

In [95]:
token_counts = np.array(counts, dtype=np.float32)
total_tokens = np.sum(token_counts)
# Avoid division by zero
adjusted_counts = np.maximum(token_counts, 1e-8)
weights = adjusted_counts / total_tokens
weights /= np.sum(weights)
weights

array([1.3540961e-03, 6.7704804e-13, 6.7704804e-13, ..., 6.7704804e-13,
       6.7704804e-13, 6.7704804e-13], dtype=float32)

In [96]:
class KittuLLM(Model):
    def __init__(self, vocab_size, embedding_dim=256, num_heads=4, ff_dim=1024, num_layers=3, dropout_rate=0.1):
        super(KittuLLM, self).__init__()
        
        # Embedding layer for input sequences
        self.embedding = Embedding(vocab_size, embedding_dim)
        
        # Transformer blocks
        self.transformer_blocks = [
            self.build_transformer_block(embedding_dim, num_heads, ff_dim, dropout_rate) 
            for _ in range(num_layers)
        ]
        
        # Feed-forward network with GlobalAveragePooling1D
        self.ffn = Sequential([ 
            GlobalAveragePooling1D(),
            Dense(ff_dim, activation='relu'),
            Dropout(dropout_rate),
            Dense(vocab_size, activation='softmax')
        ])
    
    def build_transformer_block(self, embedding_dim, num_heads, ff_dim, dropout_rate):
        # Multi-head attention
        attn_layer = MultiHeadAttention(num_heads=num_heads, key_dim=embedding_dim)
        
        # Feed-forward network
        ffn_layer = Sequential([
            Dense(ff_dim, activation='relu'),
            Dense(embedding_dim)
        ])
        
        # LayerNormalization
        norm_layer = LayerNormalization()
        
        # Dropout layer to help regularize the output
        dropout_layer = Dropout(dropout_rate)
        
        return [attn_layer, ffn_layer, norm_layer, dropout_layer]
    
    def call(self, inputs):
        # Apply embedding layer
        x = self.embedding(inputs)
        
        # Apply transformer blocks
        for attn_layer, ffn_layer, norm_layer, dropout_layer in self.transformer_blocks:
            # Multi-head attention with residual connection and normalization
            attn_output = attn_layer(x, x)
            x = norm_layer(x + attn_output)  # residual connection + normalization
            
            # Feed-forward network with residual connection and normalization
            ffn_output = ffn_layer(x)
            x = norm_layer(x + ffn_output)  # residual connection + normalization
            
            # Apply dropout for regularization
            x = dropout_layer(x)
        
        # Apply feed-forward network for output
        output = self.ffn(x)
        return output

In [97]:
model = KittuLLM(
    vocab_size=vocab_size,
    embedding_dim=embedding_dim,
    num_heads=num_heads,
    ff_dim=ff_dim,
    num_layers=num_layers,
    dropout_rate=dropout_rate
)

In [98]:
#model.build((None, input_seq_len))

In [99]:
dataset = tf.data.Dataset.from_tensor_slices((input_sequences, output_sequences))

In [100]:
lr_schedule = PolynomialDecay(
    initial_learning_rate=0.1,
    decay_steps=10000,
    end_learning_rate=1e-6
)
optimizer = Adam(learning_rate=lr_schedule)

In [101]:
class WeightedSparseCategoricalCrossentropy(tf.keras.losses.Loss):
    def __init__(self, weights, from_logits=False, reduction=tf.keras.losses.Reduction.AUTO):
        """
        Custom loss with weights for penalizing high-frequency tokens.
        Args:
            weights (array-like): Weights for each token.
            from_logits (bool): Whether `y_pred` is logits or probabilities.
        """
        super().__init__(reduction=reduction)
        self.weights = tf.constant(weights, dtype=tf.float32)
        self.from_logits = from_logits

    def call(self, y_true, y_pred):
        """
        Computes the weighted sparse categorical cross-entropy.
        Args:
            y_true: True labels, shape (batch_size,).
            y_pred: Predicted logits or probabilities, shape (batch_size, num_classes).
        Returns:
            Weighted loss value.
        """
        if self.from_logits:
            y_pred = tf.nn.softmax(y_pred)

        # Extract weights for the true class indices
        weights = tf.gather(self.weights, y_true)

        # Compute standard sparse categorical cross-entropy
        scce = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

        # Apply weights
        return scce * weights

In [102]:
model.compile(optimizer=optimizer, loss=WeightedSparseCategoricalCrossentropy(weights), metrics=['accuracy'])
history = model.fit(input_sequences, output_sequences, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
1477/1477 [==============================] - 1210s 816ms/step - loss: 0.3911 - accuracy: 0.1715 - val_loss: 0.1666 - val_accuracy: 0.1324
Epoch 2/30
1477/1477 [==============================] - 1221s 827ms/step - loss: 0.1782 - accuracy: 0.1772 - val_loss: 0.1673 - val_accuracy: 0.1324
Epoch 3/30
 201/1477 [===>..........................] - ETA: 16:34 - loss: 0.1683 - accuracy: 0.1673

KeyboardInterrupt: 

In [12]:
model.summary()

Model: "simple_transformer_lm"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       multiple                  1280000   
                                                                 
 multi_head_attention (Mult  multiple                  1051904   
 iHeadAttention)                                                 
                                                                 
 sequential (Sequential)     (None, 100, 256)          525568    
                                                                 
 dropout (Dropout)           multiple                  0         
                                                                 
 layer_normalization (Layer  multiple                  512       
 Normalization)                                                  
                                                                 
 multi_head_attention_1 (Mu  multiple        

In [13]:
test_input_list = ["Pranav Kannepalli: hola"]

In [14]:
test_input_sequences = tokenizer.texts_to_sequences(texts=test_input_list)
test_model_input = pad_sequences(test_input_sequences, maxlen=input_seq_len, padding='post', truncating='post')
test_model_input

array([[3, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
model_output = model.predict(test_model_input)
predicted_indices = np.argmax(model_output, axis=-1)
predicted_indices

1/1 [==============================] - 1s 607ms/step


array([44], dtype=int64)

In [16]:
index_to_word = tokenizer.index_word
predicted_words = [index_to_word.get(idx, "") for idx in predicted_indices]

In [17]:
output_string = " ".join(predicted_words)
output_string

'end'