In [260]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding, Dense, Dropout, LayerNormalization, MultiHeadAttention, Flatten
from tensorflow.keras import Sequential, Model
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Layer
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers.schedules import PolynomialDecay
import numpy as np
import pandas as pd

In [261]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [262]:
# Hyperparameters
vocab_size = 5000  # Vocabulary size
input_seq_len = 100    # Maximum sequence length
output_seq_len = 1
embedding_dim = 256
num_heads = 4
ff_dim = 1024
num_layers = 5
dropout_rate = 0.05
batch_size = 8
epochs = 30

In [263]:
def load_data_single_csv(filepath):
    # Load the data
    df = pd.read_csv(filepath)

    df["Message + Username"] = df["Username"] + ": " + df["Message"]

    # Initialize a list to store the conversation history
    conversation_history = []

    # Store input-output pairs
    input_texts = []
    output_texts = []

    # Iterate through the dataframe to process the conversation
    for i in range(5, len(df)):
        # Get the context of the last 5 messages (this includes messages from others as well)
        context = df.iloc[i-5:i]['Message + Username'].tolist()
        
        # The current message is the output (label) only if it was sent by you
        if df.iloc[i]['Username'] == 'Pranav Kannepalli':
            # Join the context into a single string
            context_input = "<start> " + '<sep>'.join(context) + " Pranav Kannepalli:"
            curr_message = str(df.iloc[i]['Message'])

            for i in curr_message.split(' '):
                input_texts.append(context_input)
                output_texts.append(i)
                
                context_input += ' ' + i
            
            input_texts.append(context_input)
            output_texts.append("<end>")

        
    # Create a DataFrame to store the final inputs and outputs
    training_data = pd.DataFrame({
        'input_text': input_texts,
        'output_label': output_texts
    })


    return training_data

training_data = pd.DataFrame()
for i in [2, 3]:
    filepath = f'./chat_csv\'s/chat{i}.csv'
    temp = load_data_single_csv(filepath)
    training_data = pd.concat((training_data, temp))

training_data

,input_text,output_label
0,<start> tsa 25: Messages and calls are end-to-...,image
1,<start> tsa 25: Messages and calls are end-to-...,omitted
2,<start> tsa 25: Messages and calls are end-to-...,<end>
3,<start> tsa 25: You created group “tea 25”<sep...,does
4,<start> tsa 25: You created group “tea 25”<sep...,anyone
...,...,...
2022,<start> Pranav Kannepalli: sure that works for...,possible?
2023,<start> Pranav Kannepalli: sure that works for...,<end>
2024,<start> Pranav Kannepalli: Krishna uncle?<sep>...,sounds
2025,<start> Pranav Kannepalli: Krishna uncle?<sep>...,good


In [264]:
def tokenize_and_pad(training_data):
    tokenizer = Tokenizer(num_words=vocab_size, oov_token='<OOV>')
    
    # Fit tokenizer on both input and output text
    tokenizer.fit_on_texts(training_data['input_text'].tolist() + training_data['output_label'].tolist())

    # Convert text to sequences
    input_sequences = tokenizer.texts_to_sequences(training_data['input_text'])
    output_sequences = tokenizer.texts_to_sequences(training_data['output_label'])
    
    # Pad sequences to ensure they are of equal length
    input_sequences = pad_sequences(input_sequences, maxlen=input_seq_len, padding='post', truncating='post')
    output_sequences = pad_sequences(output_sequences, maxlen=output_seq_len, padding='post', truncating='post')
    
    return input_sequences, output_sequences, tokenizer

input_sequences, output_sequences, tokenizer = tokenize_and_pad(training_data)
input_sequences, output_sequences

(array([[  8, 112, 338, ...,   0,   0,   0],
        [  8, 112, 338, ...,   0,   0,   0],
        [  8, 112, 338, ...,   0,   0,   0],
        ...,
        [  8,   3,   4, ...,   0,   0,   0],
        [  8,   3,   4, ...,   0,   0,   0],
        [  8,   3,   4, ...,   0,   0,   0]]),
 array([[ 85],
        [ 84],
        [ 44],
        ...,
        [135],
        [ 51],
        [ 44]]))

In [265]:
class SimpleTransformerLM(Model):
    def __init__(self, vocab_size, embedding_dim=256, num_heads=4, ff_dim=1024, num_layers=5, dropout_rate=0.05):
        super(SimpleTransformerLM, self).__init__()
        
        # Embedding layer
        self.embedding = Embedding(vocab_size, embedding_dim)
        
        # Transformer encoder layers
        self.transformer_blocks = [
            self.build_transformer_block(embedding_dim, num_heads, ff_dim, dropout_rate) for _ in range(num_layers)
        ]
        
        # Final output layer
        self.ffn = Sequential([
            Dense(ff_dim, activation='relu'),
            Flatten(),
            Dense(vocab_size, activation='softmax')
        ])
    
    def build_transformer_block(self, embedding_dim, num_heads, ff_dim, dropout_rate):
        # Multi-Head Attention
        attn_layer = MultiHeadAttention(num_heads=num_heads, key_dim=embedding_dim)
        
        # Feed-forward network
        ffn_layer = Sequential([
            Dense(ff_dim, activation='relu'),
            Dense(embedding_dim)
        ])
        
        # Dropout and LayerNormalization
        dropout_layer = Dropout(dropout_rate)
        norm_layer = LayerNormalization()
        
        return [attn_layer, ffn_layer, dropout_layer, norm_layer]
    
    def call(self, inputs):
        x = self.embedding(inputs)
        
        # Apply each transformer block
        for attn_layer, ffn_layer, dropout_layer, norm_layer in self.transformer_blocks:
            # MultiHead Attention
            attn_output = attn_layer(x, x)
            x = tf.keras.layers.Add()([x, attn_output])  # Residual connection
            x = norm_layer(x)
            
            # Feed-forward layer
            ffn_output = ffn_layer(x)
            x = tf.keras.layers.Add()([x, ffn_output])  # Residual connection
            x = norm_layer(x)
            
            # Dropout
            x = dropout_layer(x)
        
        # Output layer
        output = self.ffn(x)
        return output

# Example usage
def generate_sequence(model, start_token, sep_token, end_token, max_len=20):
    model.eval()
    input_seq = tf.constant([[start_token]])  # Shape: (1, 1)
    generated_seq = [start_token]

    for _ in range(max_len):
        output = model(input_seq)
        next_token = tf.argmax(output[:, -1, :], axis=-1).numpy().item()  # Get the last predicted token
        generated_seq.append(next_token)
        
        if next_token == end_token:
            break  # Stop generating if the <end> token is predicted
        
        input_seq = tf.concat([input_seq, tf.constant([[next_token]])], axis=1)
    
    return generated_seq

In [266]:
model = SimpleTransformerLM(
    vocab_size=vocab_size,
    embedding_dim=embedding_dim,
    num_heads=num_heads,
    ff_dim=ff_dim,
    num_layers=num_layers,
    dropout_rate=dropout_rate
)

In [267]:
#model.build((None, input_seq_len))

In [268]:
dataset = tf.data.Dataset.from_tensor_slices((input_sequences, output_sequences))

In [269]:
lr_schedule = PolynomialDecay(
    initial_learning_rate=0.1,
    decay_steps=10000,
    end_learning_rate=1e-6
)
optimizer = Adam(learning_rate=lr_schedule)

In [270]:
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(input_sequences, output_sequences, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30


KeyboardInterrupt: 

In [243]:
model.summary()

Model: "simple_transformer_lm_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_24 (Embedding)    multiple                  1280000   
                                                                 
 multi_head_attention_255 (  multiple                  1051904   
 MultiHeadAttention)                                             
                                                                 
 sequential_193 (Sequential  (8, 100, 256)             525568    
 )                                                               
                                                                 
 dropout_364 (Dropout)       multiple                  0         
                                                                 
 layer_normalization_395 (L  multiple                  512       
 ayerNormalization)                                              
                                           

In [255]:
test_input_list = ["Pranav Kannepalli: hola"]

In [256]:
test_input_sequences = tokenizer.texts_to_sequences(texts=test_input_list)
test_model_input = pad_sequences(test_input_sequences, maxlen=input_seq_len, padding='post', truncating='post')
test_model_input

array([[3, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [257]:
model_output = model.predict(test_model_input)
predicted_indices = np.argmax(model_output, axis=-1)
predicted_indices

1/1 [==============================] - 0s 89ms/step


array([18], dtype=int64)

In [258]:
index_to_word = tokenizer.index_word
predicted_words = [index_to_word.get(idx, "") for idx in predicted_indices]

In [259]:
output_string = " ".join(predicted_words)
output_string

'yeah'